CREATE DATABASE LANCHONETE;
use LANCHONETE;

CREATE TABLE cardápio(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL
);

CREATE TABLE lanche(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL
    id_genero INT NOT NULL,
    FOREIGN KEY (id_genero) REFERENCES generos (id)
);
